from building import *
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add LittlevGL common include
inc = inc + [cwd]
inc = inc + [cwd + "/../../bsp/stm32f4xx-HAL/drivers"]

# add LittlevGL basic code
src = src + Glob('./iic_eeprom.c')

LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu -g -W'

group = DefineGroup('RTT_METER_EEPROM', src, depend = ['RT_USING_COMPONENTS_METER_EEPROM'], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
